# apt-daily.service.d
- when: unattended_upgrades.apt_daily.service.override != None
  block:

  # mkdir
  - name: Mkdir /etc/systemd/system/apt-daily.service.d
    become: true
    ansible.builtin.file:
      path: /etc/systemd/system/apt-daily.service.d
      state: directory
      owner: root
      group: root
      mode: o=rwx,g=rx,o=rx
  
  # cp service unit files
  - name: Copy to /etc/systemd/system/apt-daily.service.d/override.conf
    become: true
    notify: Systemd daemon-reload
    ansible.builtin.copy:
      src: "apt-daily.service.d/{{ unattended_upgrades.apt_daily.service.override }}"
      dest: /etc/systemd/system/apt-daily.service.d/override.conf
      force: true
      owner: root
      group: root
      mode: u=rw,g=r,o=r

# enable/disable service
- name: Enabled {{ unattended_upgrades.apt_daily.service.enabled }} apt-daily.service
  become: true
  ansible.builtin.systemd_service:
    enabled: "{{ unattended_upgrades.apt_daily.service.enabled }}"
    name: apt-daily.service

# apt-daily.timer.d
- when: unattended_upgrades.apt_daily.timer.override != None
  block:

  # mkdir
  - name: Mkdir /etc/systemd/system/apt-daily.timer.d
    become: true
    ansible.builtin.file:
      path: /etc/systemd/system/apt-daily.timer.d
      state: directory
      owner: root
      group: root
      mode: o=rwx,g=rx,o=rx

  # cp timer unit files
  - name: Copy to /etc/systemd/system/apt-daily.timer.d/override.conf
    become: true
    notify: Systemd daemon-reload
    ansible.builtin.copy:
      src: "apt-daily.timer.d/{{ unattended_upgrades.apt_daily.timer.override }}"
      dest: /etc/systemd/system/apt-daily.timer.d/override.conf
      force: true
      owner: root
      group: root
      mode: u=rw,g=r,o=r

# enable/disable timer
- name: Enabled {{ unattended_upgrades.apt_daily.timer.enabled }} apt-daily.timer
  become: true
  ansible.builtin.systemd_service:
    enabled: "{{ unattended_upgrades.apt_daily.timer.enabled }}"
    name: apt-daily.timer