---
# apt install
- name: Apt install {{ unattended_upgrades_apt_install }}
  become: true
  ansible.builtin.apt:
    state: present
    name: "{{ unattended_upgrades_apt_install }}"

# apt remove
- name: Apt remove {{ unattended_upgrades_apt_remove }}
  become: true
  ansible.builtin.apt:
    state: absent
    name: "{{ unattended_upgrades_apt_remove }}"