# apt listchanges
- name: Apt state {{ unattended_upgrades.listchanges.apt.state }}
  become: true
  ansible.builtin.apt:
    state: "{{ unattended_upgrades.listchanges.apt.state }}"
    name: apt-listchanges

# template listchanges
- when: unattended_upgrades.listchanges.config.src != None
  name: Template /etc/apt/listchanges.conf
  become: true
  ansible.builtin.template:
    src: listchanges.conf.j2
    dest: /etc/apt/listchanges.conf
    force: true # the remote file will be replaced when contents are different than the source
    owner: root
    group: root
    mode: u=rw,g=r,o=r