---
- name: unattended-upgrades role
  tags:
  - unattended-upgrades
  block:

  # debug
  - when: false
    ansible.builtin.debug:
      msg: "{{ unattended_upgrades }}"
  
  # check
  - name: Check vars for unattended-upgrades role
    ansible.builtin.assert:
      that:
      - unattended_upgrades_config_template != None
      - unattended_upgrades_config_vars['mail'] != None

  # install
  - ansible.builtin.import_tasks: install.yml

  # systemd
  - ansible.builtin.import_tasks: systemd.yml

  # template config file
  - name: Template {{ unattended_upgrades_config_dst }}
    when: unattended_upgrades_config_template != None
    become: true
    notify: systemctl restart unattended-upgrades.service
    ansible.builtin.template:
      src: "{{ unattended_upgrades_config_template }}"
      dest: "{{ unattended_upgrades_config_dst }}"
      force: true # file will be replaced when contents are different than the source (default) 
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  # template listchanges
  - when:
    - "'apt-listchanges' in unattended_upgrades_install_apt"
    - unattended_upgrades_listchanges_config != None
    name: Template {{ unattended_upgrades_listchanges_config }}
    become: true
    ansible.builtin.template:
      src: "{{ unattended_upgrades_listchanges_config }}"
      dest: /etc/apt/listchanges.conf
      force: true # the remote file will be replaced when contents are different than the source
      owner: root
      group: root
      mode: u=rw,g=r,o=r